#!/usr/bin/env bash

# Create a list of git repositories that can be used to
# perform operations across all repos.

[[ -z "$REPOS_ROOT" ]] && REPOS_ROOT="$HOME"

repos=$(
    {
        ls -d $REPOS_ROOT/*/.git;
        ls -d $REPOS_ROOT-personal/*/.git;
        ls -d $REPOS_ROOT/github/*/.git;
        ls -d $REPOS_ROOT/gitlab/*/.git;
    } 2>/dev/null | sort;
)

for repo in $repos; do
    dirname $repo
done
